# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 693bbd2cc626bac0c6e88628457498ca8e606f3a3b69f422a0bd9ec22c02453f2f4637d6bba390573f8a5e9b7a3092c193e7409c7cfd1223e064b45a31099499

test:
  secret_key_base: a2a18b32bf347493826c2c843acafa0198409c41666be02509f2b0be111c2e97e9647871fe8414dba061dc9a045449c2575e56e1af670aca9cef684ff565ef35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
